import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header";

const MyLocalFont = localFont({
  src: [
    {
      path: '../../public/fonts/GmarketSansTTFLight.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GmarketSansTTFMedium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/GmarketSansTTFBold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="flex justify-center bg-white">
      <body className="w-full sm:w-[640px] bg-white">
        <div className=" fixed top-0 w-full sm:w-[640px] z-0">
          <Header />
        </div>
        <div className="mt-20 px-5 sm:px-20">
          {children}
        </div>



      </body>
    </html >
  );
}
